#!/bin/sh
# Gradle start up script for POSIX generated by Gradle.
#
# 说明：本仓库的 gradle-wrapper.jar 随仓库一起提交（见 gradle/wrapper/）。
# 官方 wrapper jar 的 MANIFEST 没有 Main-Class，因此必须用 -classpath 指定主类，
# 不能用 java -jar。缺失 jar 时才回退到系统 gradle（仅作兜底，CI 上不要依赖它）。

PRG="$0"
while [ -h "$PRG" ]; do
  ls=$(ls -ld "$PRG")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=$(dirname "$PRG")/"$link"
  fi
done
APP_HOME=$(cd "$(dirname "$PRG")" && pwd)
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ -f "$WRAPPER_JAR" ]; then
  exec java ${GRADLE_OPTS} -classpath "$WRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
fi

echo "gradle-wrapper.jar not found under $APP_HOME/gradle/wrapper; falling back to system gradle" >&2
exec gradle "$@"
